# Generated by Django 4.1.3 on 2023-01-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="channel_name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
