# Generated by Django 4.1.3 on 2023-01-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_course_channel_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="tag",
            field=models.CharField(default="", max_length=100),
        ),
    ]
