# Generated by Django 4.1.5 on 2023-01-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_remove_course_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="notes",
            field=models.TextField(default="Type your notes here..."),
        ),
    ]
